apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: { { .Release.Namespace | quote } }
  labels:
    { { - include "app.labels" . | nindent 4 } }
type: Opaque
data:
  redis-password: {{- if .Values.redisPassword -}}
    {{ .Values.redisPassword | b64enc }}
  {{- else -}}
  {{ randAlphaNum 12 | b64enc }}
  {{- end -}}
