apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}-master
  namespace: {{ .Release.Namespace | quote }}
  labels:
    { { - include "app.labels" . | nindent 4 } }
      { { - include "app.extraLabels" . | nindent 4 } }
spec:
  selector:
    { { - include "app.labels" . | nindent 4 } }
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}-replica
  namespace: {{ .Release.Namespace | quote }}
  labels:
    { { - include "app.labels" . | nindent 4 } }
      { { - include "app.extraLabels" . | nindent 4 } }
spec:
  selector:
    { { - include "app.labels" . | nindent 4 } }
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
