apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: { { .Release.Namespace | quote } }
  labels:
    { { - include "app.labels" . | nindent 4 } }
spec:
  serviceName: redis-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      { { - include "app.labels" . | nindent 4 } }
  template:
    metadata:
      labels:
        { { - include "app.labels" . | nindent 4 } }
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          resources:
            limits:
              cpu: {{ .Values.master.resources.limits.cpu }}
              memory: {{ .Values.master.resources.limits.memory }}
            requests:
              cpu: {{ .Values.master.resources.requests.cpu }}
              memory: {{ .Values.master.resources.requests.memory }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
