{{- if .Values.pvc.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  storageClassName: {{ .Values.pvc.storageClass }}
  volumeMode: Filesystem
{{- end }}
