{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "pods"
      - "services"
      - "endpoints"
    verbs:
      - "get"
      - "list"
      - "watch"
{{- end -}}
