{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val :=  .Values.secret }}
  {{ $key | nindent 2 }}: {{ $val | quote }}
{{- end }}
{{- end -}}
