apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{- if .Values.postgresqlPassword -}}
    {{ .Values.postgresqlPassword | b64enc }}
  {{- else -}}
  {{ randAlphaNum 12 | b64enc }}
  {{- end -}}
