apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    { { - include "app.labels" . | nindent 4 } }
      { { - include "app.extraLabels" . | nindent 4 } }
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
